services:

  postgres:
    image: postgres:15
    container_name: trip_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # Default DB - though we are making multiple
      POSTGRES_DB: ${POSTGRES_DB} 
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - trip_pg_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: trip_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    container_name: trip_keycloak
    restart: unless-stopped
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${KC_DB_USER}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_HOSTNAME: localhost
      KC_HTTP_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ../keycloak/realm-export:/opt/keycloak/data/import

  nginx:
    image: nginx:alpine
    container_name: trip_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - keycloak
      - user-service

  user-service:
    build:
      context: ../user-service
      dockerfile: Dockerfile
    container_name: trip_user_service
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: ${USER_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${USER_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${USER_DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "${USER_SERVICE_PORT}:8081"
    depends_on:
      - postgres
      - keycloak

volumes:
  trip_pg_data: