server:
  port: 8083

spring:
  application:
    name: itinerary-service
  datasource:
    url: jdbc:postgresql://localhost:5432/itinerarydb
    username: tripuser
    password: tripsecret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Logging
logging:
  level:
    com.triptribe: DEBUG
